symbolsMn   = [[ "H",   "", "NT",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",  "-",   "", "He"],
		       ["Li", "Be",   "",   "",   "",   "",   "",   "", "bc",  "-",   "",   "",  "B",  "C",  "N",  "O",  "F", "Ne"],
		       ["Na", "Mg",   "",   "",   "",   "",   "",   "",   "",   "",   "",   "", "Al", "Si",  "P",  "S", "Cl", "Ar"],
		       ["K",  "Ca", "Sc", "Ti",  "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr"],
		       ["Rb", "Sr",  "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te",  "I", "Xe"],
		       ["Cs", "Ba", "La", "Hf", "Ta",  "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn"],
			   ["Fr", "Ra", "Ac", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og"]]

symbolsXtra = [["Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu"],
			   ["Th", "Pa",  "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr"]]

# Meaning symbols atomic number list
sanl = ["H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne",
		"Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar",
		"K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr",
		"Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te",  "I", "Xe",
		"Cs", "Ba", "La",
		"Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
		"Hf", "Ta",  "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn",
		"Fr", "Ra", "Ac",
		"Th", "Pa",  "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr",
		"Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og"]

englishNames = {
	"H" : "hydrogen",
	"He": "helium",
	"Li": "lithium",
	"Be": "beryllium",
	"B" : "boron",
	"C" : "carbon",
	"N" : "nitrogen",
	"O" : "oxygen",
	"F" : "fluorine",
	"Ne": "neon",
	"Na": "sodium",
	"Mg": "magnesium",
	"Al": "aluminium",
	"Si": "silicon",
	"P" : "phosphorus",
	"S" : "sulfur",
	"Cl": "chlorine",
	"Ar": "argon",
	"K" : "potassium",
	"Ca": "calcium",
	"Sc": "scandium",
	"Ti": "titanium",
	"V" : "vanadium",
	"Cr": "chromium",
	"Mn": "manganese",
	"Fe": "iron",
	"Co": "cobalt",
	"Ni": "nickel",
	"Cu": "copper",
	"Zn": "zinc",
	"Ga": "gallium",
	"Ge": "germanium",
	"As": "arsenic",
	"Se": "selenium",
	"Br": "bromine",
	"Kr": "krypton",
	"Rb": "rubidium",
	"Sr": "strontium",
	"Y" : "yttrium",
	"Zr": "zirconium",
	"Nb": "niobium",
	"Mo": "molybdenum",
	"Tc": "technetium",
	"Ru": "ruthenium",
	"Rh": "rhodium",
	"Pd": "palladium",
	"Ag": "silver",
	"Cd": "cadmium",
	"In": "indium",
	"Sn": "tin",
	"Sb": "antimony",
	"Te": "tellurium",
	"I" : "iodine",
	"Xe": "xenon",
	"Cs": "caesium",
	"Ba": "barium",
	"La": "lanthanum",
	"Ce": "cerium",
	"Pr": "praseodymium",
	"Nd": "neodymium",
	"Pm": "promethium",
	"Sm": "samarium",
	"Eu": "europium",
	"Gd": "gadolinium",
	"Tb": "terbium",
	"Dy": "dysprosium",
	"Ho": "holmium",
	"Er": "erbium",
	"Tm": "thulium",
	"Yb": "ytterbium",
	"Lu": "lutetium",
	"Hf": "hafnium",
	"Ta": "tantalum",
	"W" : "tungsten",
	"Re": "rhenium",
	"Os": "osmium",
	"Ir": "iridium",
	"Pt": "platinum",
	"Au": "gold",
	"Hg": "mercury",
	"Tl": "thallium",
	"Pb": "lead",
	"Bi": "bismuth",
	"Po": "polonium",
	"At": "astatine",
	"Rn": "radon",
	"Fr": "francium",
	"Ra": "radium",
	"Ac": "actinium",
	"Th": "thorium",
	"Pa": "protactinium",
	"U" : "uranium",
	"Np": "neptunium",
	"Pu": "plutonium",
	"Am": "americium",
	"Cm": "curium",
	"Bk": "berkelium",
	"Cf": "californium",
	"Es": "einsteinium",
	"Fm": "fermium",
	"Md": "mendelevium",
	"No": "nobelium",
	"Lr": "lawrencium",
	"Rf": "rutherfordium",
	"Db": "dubnium",
	"Sg": "seaborgium",
	"Bh": "bohrium",
	"Hs": "hassium",
	"Mt": "meitnerium",
	"Ds": "darmstadtium",
	"Rg": "roentgenium",
	"Cn": "copernicium",
	"Nh": "nihonium",
	"Fl": "flerovium",
	"Mc": "moscovium",
	"Lv": "livermorium",
	"Ts": "tennessine",
	"Og": "oganesson"
}

englishNamesU = {
	"H": "Hydrogen",
	"He": "Helium",
	"Li": "Lithium",
	"Be": "Beryllium",
	"B" : "Boron",
	"C" : "Carbon",
	"N" : "Nitrogen",
	"O" : "Oxygen",
	"F" : "Fluorine",
	"Ne": "Neon",
	"Na": "Sodium",
	"Mg": "Magnesium",
	"Al": "Aluminium",
	"Si": "Silicon",
	"P" : "Phosphorus",
	"S" : "Sulfur",
	"Cl": "Chlorine",
	"Ar": "Argon",
	"K" : "Potassium",
	"Ca": "Calcium",
	"Sc": "Scandium",
	"Ti": "Titanium",
	"V" : "Vanadium",
	"Cr": "Chromium",
	"Mn": "Manganese",
	"Fe": "Iron",
	"Co": "Cobalt",
	"Ni": "Nickel",
	"Cu": "Copper",
	"Zn": "Zinc",
	"Ga": "Gallium",
	"Ge": "Germanium",
	"As": "Arsenic",
	"Se": "Selenium",
	"Br": "Bromine",
	"Kr": "Krypton",
	"Rb": "Rubidium",
	"Sr": "Strontium",
	"Y" : "Yttrium",
	"Zr": "Zirconium",
	"Nb": "Niobium",
	"Mo": "Molybdenum",
	"Tc": "Technetium",
	"Ru": "Ruthenium",
	"Rh": "Rhodium",
	"Pd": "Palladium",
	"Ag": "Silver",
	"Cd": "Cadmium",
	"In": "Indium",
	"Sn": "Tin",
	"Sb": "Antimony",
	"Te": "Tellurium",
	"I" : "Iodine",
	"Xe": "Xenon",
	"Cs": "Caesium",
	"Ba": "Barium",
	"La": "Lanthanum",
	"Ce": "Cerium",
	"Pr": "Praseodymium",
	"Nd": "Neodymium",
	"Pm": "Promethium",
	"Sm": "Samarium",
	"Eu": "Europium",
	"Gd": "Gadolinium",
	"Tb": "Terbium",
	"Dy": "Dysprosium",
	"Ho": "Holmium",
	"Er": "Erbium",
	"Tm": "Thulium",
	"Yb": "Ytterbium",
	"Lu": "Lutetium",
	"Hf": "Hafnium",
	"Ta": "Tantalum",
	"W" : "Tungsten",
	"Re": "Rhenium",
	"Os": "Osmium",
	"Ir": "Iridium",
	"Pt": "Platinum",
	"Au": "Gold",
	"Hg": "Mercury",
	"Tl": "Thallium",
	"Pb": "Lead",
	"Bi": "Bismuth",
	"Po": "Polonium",
	"At": "Astatine",
	"Rn": "Radon",
	"Fr": "Francium",
	"Ra": "Radium",
	"Ac": "Actinium",
	"Th": "Thorium",
	"Pa": "Protactinium",
	"U" : "Uranium",
	"Np": "Neptunium",
	"Pu": "Plutonium",
	"Am": "Americium",
	"Cm": "Curium",
	"Bk": "Berkelium",
	"Cf": "Californium",
	"Es": "Einsteinium",
	"Fm": "Fermium",
	"Md": "Mendelevium",
	"No": "Nobelium",
	"Lr": "Lawrencium",
	"Rf": "Rutherfordium",
	"Db": "Dubnium",
	"Sg": "Seaborgium",
	"Bh": "Bohrium",
	"Hs": "Hassium",
	"Mt": "Meitnerium",
	"Ds": "Darmstadtium",
	"Rg": "Roentgenium",
	"Cn": "Copernicium",
	"Nh": "Nihonium",
	"Fl": "Flerovium",
	"Mc": "Moscovium",
	"Lv": "Livermorium",
	"Ts": "Tennessine",
	"Og": "Oganesson"
}